-- Seed: categorias e itens de stock da pizzaria (executar após migrations 005–008).
-- Categorias são inseridas primeiro; itens referenciam por nome da categoria.

-- 1) Categorias (distintas do teu JSON)
insert into public.stock_categories (name)
values
  ('Frutas'),
  ('Bebidas não alcoólicas'),
  ('Temperos'),
  ('Carnes'),
  ('Óleos'),
  ('Molhos'),
  ('Vegetais'),
  ('Doces'),
  ('Geral'),
  ('Massas'),
  ('Queijos'),
  ('Bebidas alcoolicas');

-- 2) Itens (name, sku, categoria, type, is_sellable, sale_price, min_stock, base_unit)
-- type: beverage (Bebidas), packaging (Embalagem/Saco), other (Chaveiro), rest ingredient
insert into public.stock_items (name, sku, category_id, type, is_sellable, sale_price, min_stock, base_unit)
select v.name, v.sku, c.id, v.type::public.stock_item_type, v.is_sellable, v.sale_price, v.min_stock, v.base_unit::public.stock_base_unit
from (
  values
    ('Abacaxi', '30017', 'Frutas', 'ingredient', false, null, 200, 'g'),
    ('Água Solan Cabras 33cl', '180008', 'Bebidas não alcoólicas', 'beverage', true, 1.50, 200, 'un'),
    ('Água Solan Cabras Com Gás 33cl', '180001', 'Bebidas não alcoólicas', 'beverage', true, 1.50, 200, 'un'),
    ('Alho Granulado Makro', '360003', 'Temperos', 'ingredient', false, null, 600, 'g'),
    ('Atum', '90001', 'Carnes', 'ingredient', false, null, 200, 'g'),
    ('Azeite', '1', 'Óleos', 'ingredient', false, null, 200, 'g'),
    ('Azeite Trufado', '30011', 'Molhos', 'ingredient', false, null, 200, 'g'),
    ('Azeitona Preta', '30013', 'Temperos', 'ingredient', false, null, 200, 'g'),
    ('Azeitonas', '10', 'Vegetais', 'ingredient', false, null, 150, 'g'),
    ('Banana', '60001', 'Frutas', 'ingredient', false, null, 200, 'g'),
    ('Brigadeiro', '30024', 'Doces', 'ingredient', false, null, 200, 'g'),
    ('Brigadeiro de Oreo', '30026', 'Doces', 'ingredient', false, null, 200, 'g'),
    ('Camarão', '30016', 'Carnes', 'ingredient', false, null, 200, 'g'),
    ('Canela Pó Makro', '360004', 'Temperos', 'ingredient', false, null, 200, 'g'),
    ('Cebola Crispy', '120001', 'Vegetais', 'ingredient', false, null, 200, 'g'),
    ('Cebola Roxa', '30012', 'Vegetais', 'ingredient', false, null, 200, 'g'),
    ('Chaveiro Angry Box', '450001', 'Geral', 'other', true, 2.00, 5, 'un'),
    ('Coca Cola 33cl', '180002', 'Bebidas não alcoólicas', 'beverage', true, 2.50, 10, 'un'),
    ('Coca Cola Zero 33cl', '180003', 'Bebidas não alcoólicas', 'beverage', true, 2.50, 10, 'un'),
    ('Cogumelos', '9', 'Vegetais', 'ingredient', false, null, 200, 'g'),
    ('Creme de Alho', '240004', 'Geral', 'ingredient', false, null, 1000, 'g'),
    ('Doce de Leite', '30028', 'Doces', 'ingredient', false, null, 200, 'g'),
    ('Embalagem takeaway', '210002', 'Geral', 'packaging', true, 0, 200, 'un'),
    ('Farinha Caputo Saccorosso', '30001', 'Massas', 'ingredient', false, null, 1000, 'g'),
    ('Fermento Fermipan', '30004', 'Massas', 'ingredient', false, null, 100, 'g'),
    ('Frango', '30021', 'Carnes', 'ingredient', false, null, 200, 'g'),
    ('Gorgonzola', '30020', 'Queijos', 'ingredient', false, null, 200, 'g'),
    ('Granulado', '30025', 'Doces', 'ingredient', false, null, 200, 'g'),
    ('Guaraná Antartica 33cl', '180004', 'Bebidas não alcoólicas', 'beverage', true, 2.50, 200, 'un'),
    ('Ice Tea Lipton limão 33cl', '180005', 'Bebidas não alcoólicas', 'beverage', true, 2.50, 200, 'un'),
    ('Ice Tea Lipton pêssego 33cl', '180006', 'Bebidas não alcoólicas', 'beverage', true, 2.50, 200, 'un'),
    ('Maestra Dunkel 20cl', '180014', 'Bebidas alcoolicas', 'beverage', true, 4.00, 200, 'cl'),
    ('Maestra Dunkel 40cl', '180009', 'Bebidas alcoolicas', 'beverage', true, 4.00, 200, 'cl'),
    ('Maionese de Alho', '30014', 'Molhos', 'ingredient', false, null, 200, 'g'),
    ('Malte Enzimática', '240001', 'Massas', 'ingredient', false, null, 1000, 'g'),
    ('Manjericão', '12', 'Temperos', 'ingredient', false, null, 50, 'g'),
    ('Mel Makro', '30015', 'Doces', 'ingredient', false, null, 2000, 'g'),
    ('Molho de Alho', '30006', 'Molhos', 'ingredient', false, null, 200, 'g'),
    ('Molho de tomate Angry Box', '4', 'Molhos', 'ingredient', false, null, 3, 'g'),
    ('Molho de tomate Mutti', '330001', 'Molhos', 'ingredient', false, null, 3, 'g'),
    ('Molho de Trufa', '30010', 'Molhos', 'ingredient', false, null, 200, 'g'),
    ('Oregão Makro', '360001', 'Temperos', 'ingredient', false, null, 140, 'g'),
    ('Oreo', '30027', 'Doces', 'ingredient', false, null, 200, 'g'),
    ('Parmesão', '30019', 'Queijos', 'ingredient', false, null, 200, 'g'),
    ('Pepperoni Porminho', '8', 'Carnes', 'ingredient', false, null, 2, 'g'),
    ('Pesto', '3', 'Molhos', 'ingredient', false, null, 200, 'g'),
    ('Pimenta Piri Piri', '30007', 'Temperos', 'ingredient', false, null, 400, 'g'),
    ('Queijo Camembert Metro', '240003', 'Queijos', 'ingredient', false, null, 1, 'g'),
    ('Queijo Cheddar Villas', '240002', 'Queijos', 'ingredient', false, null, 1, 'g'),
    ('Queijo Gorgonzola Casa Leonardi', '6', 'Queijos', 'ingredient', false, null, 0.50, 'g'),
    ('Queijo Grana Padano Ralado Makro', '300001', 'Queijos', 'ingredient', false, null, 0.20, 'g'),
    ('Queijo Grana Padano Zanetti', '5', 'Queijos', 'ingredient', false, null, 0.30, 'g'),
    ('Queijo Mozzarela Eurial', '2', 'Queijos', 'ingredient', false, null, 20, 'kg'),
    ('Queijo Provolone', '7', 'Queijos', 'ingredient', false, null, 0.50, 'g'),
    ('Reblochon', '30018', 'Queijos', 'ingredient', false, null, 200, 'g'),
    ('Saco Bolt', '390001', 'Geral', 'packaging', true, 0.37, 50, 'un'),
    ('Sal Vatel', '30003', 'Temperos', 'ingredient', false, null, 1000, 'g'),
    ('Salsa Makro', '270001', 'Temperos', 'ingredient', false, null, 60, 'g'),
    ('San Miguel Especial 20cl', '180010', 'Bebidas alcoolicas', 'beverage', true, 3.00, 200, 'cl'),
    ('San Miguel Especial 40cl', '180011', 'Bebidas alcoolicas', 'beverage', true, 4.20, 200, 'cl'),
    ('San Miguel Fresca 33cl', '180012', 'Bebidas alcoolicas', 'beverage', true, 3.00, 5, 'un'),
    ('San Miguel Mini 25cl', '420001', 'Bebidas alcoolicas', 'beverage', true, 2.50, 5, 'un'),
    ('San Miguel Radler 20cl', '180015', 'Bebidas alcoolicas', 'beverage', true, 4.50, 200, 'cl'),
    ('San Miguel Radler 40cl', '180016', 'Bebidas alcoolicas', 'beverage', true, 4.50, 200, 'cl'),
    ('Sangria Sarango 20cl', '180017', 'Bebidas alcoolicas', 'beverage', true, 4.00, 200, 'cl'),
    ('Sangria Sarango 40cl', '180018', 'Bebidas alcoolicas', 'beverage', true, 4.00, 200, 'cl'),
    ('Seven Up limão zero 33cl', '180007', 'Bebidas não alcoólicas', 'beverage', true, 2.50, 200, 'un'),
    ('Tomilho Makro', '360002', 'Temperos', 'ingredient', false, null, 160, 'g')
) as v(name, sku, cat_name, type, is_sellable, sale_price, min_stock, base_unit)
join public.stock_categories c on c.name = v.cat_name;
