import type { FinancialType } from "../entities/cost-center-category.js";

export interface DefaultCategorySeed {
  code: string;
  name: string;
  financialType: FinancialType;
  affectsDre: boolean;
  affectsCashflow: boolean;
  affectsProfitability: boolean;
  requiresChannel: boolean;
  requiresAllocation: boolean;
}

export interface DefaultGroupSeed {
  code: string;
  name: string;
  description: string;
  sortOrder: number;
  categories: DefaultCategorySeed[];
}

export const DEFAULT_COST_CENTERS: DefaultGroupSeed[] = [
  {
    code: "OPD",
    name: "Operação Direta",
    description: "Custos diretamente ligados à produção e venda",
    sortOrder: 1,
    categories: [
      {
        code: "OPD.01",
        name: "CMV / Ingredientes",
        financialType: "cmv",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "OPD.02",
        name: "Bebidas",
        financialType: "cmv",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "OPD.03",
        name: "Embalagens",
        financialType: "variable_cost",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: true,
        requiresAllocation: false,
      },
      {
        code: "OPD.04",
        name: "Taxas de Apps Delivery",
        financialType: "variable_cost",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: true,
        requiresAllocation: false,
      },
      {
        code: "OPD.05",
        name: "Taxas de Pagamento",
        financialType: "variable_cost",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "OPD.06",
        name: "Quebras & Desperdícios",
        financialType: "cmv",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: false,
        requiresAllocation: false,
      },
    ],
  },
  {
    code: "PES",
    name: "Pessoal",
    description: "Salários, encargos, extras e terceiros",
    sortOrder: 2,
    categories: [
      {
        code: "PES.01",
        name: "Salários",
        financialType: "personnel",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
      {
        code: "PES.02",
        name: "Encargos",
        financialType: "personnel",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
      {
        code: "PES.03",
        name: "Extras / Bonificações",
        financialType: "personnel",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
      {
        code: "PES.04",
        name: "Serviços Terceirizados",
        financialType: "personnel",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
    ],
  },
  {
    code: "EST",
    name: "Estrutura & Instalações",
    description: "Custos da loja e infraestrutura",
    sortOrder: 3,
    categories: [
      {
        code: "EST.01",
        name: "Renda / Aluguel",
        financialType: "fixed_opex",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
      {
        code: "EST.02",
        name: "Energia",
        financialType: "fixed_opex",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
      {
        code: "EST.03",
        name: "Água / Gás",
        financialType: "fixed_opex",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: true,
      },
      {
        code: "EST.04",
        name: "Internet / Telecom",
        financialType: "fixed_opex",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "EST.05",
        name: "Limpeza & Higiene",
        financialType: "fixed_opex",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "EST.06",
        name: "Manutenção",
        financialType: "fixed_opex",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
    ],
  },
  {
    code: "ADM",
    name: "Administrativo & Financeiro",
    description: "Gestão, sistemas, bancos e contabilidade",
    sortOrder: 4,
    categories: [
      {
        code: "ADM.01",
        name: "Contabilidade",
        financialType: "administrative",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "ADM.02",
        name: "Software & Sistemas",
        financialType: "administrative",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "ADM.03",
        name: "Taxas Bancárias",
        financialType: "financial",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "ADM.04",
        name: "Jurídico",
        financialType: "administrative",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "ADM.05",
        name: "Seguros / Licenças",
        financialType: "administrative",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
    ],
  },
  {
    code: "MKT",
    name: "Marketing & Comercial",
    description: "Aquisição, marca, promoções e parcerias",
    sortOrder: 5,
    categories: [
      {
        code: "MKT.01",
        name: "Anúncios Pagos",
        financialType: "marketing",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "MKT.02",
        name: "Conteúdo / Design / Fotografia",
        financialType: "marketing",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "MKT.03",
        name: "Promoções / Ofertas",
        financialType: "marketing",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: true,
        requiresChannel: true,
        requiresAllocation: false,
      },
      {
        code: "MKT.04",
        name: "Parcerias / Influencers",
        financialType: "marketing",
        affectsDre: true,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
    ],
  },
  {
    code: "CAP",
    name: "Investimentos / CAPEX",
    description: "Equipamentos, obras e ativos",
    sortOrder: 6,
    categories: [
      {
        code: "CAP.01",
        name: "Equipamentos",
        financialType: "capex",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "CAP.02",
        name: "Obras & Melhorias",
        financialType: "capex",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "CAP.03",
        name: "Hardware",
        financialType: "capex",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "CAP.04",
        name: "Mobiliário",
        financialType: "capex",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
    ],
  },
  {
    code: "FDR",
    name: "Fora da DRE",
    description: "Movimentos financeiros que não são despesa operacional",
    sortOrder: 7,
    categories: [
      {
        code: "FDR.01",
        name: "Participação / Retirada de Sócios",
        financialType: "off_dre",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "FDR.02",
        name: "Transferências Internas",
        financialType: "internal_transfer",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "FDR.03",
        name: "IVA a Recuperar / IVA a Pagar",
        financialType: "fiscal",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "FDR.04",
        name: "Empréstimos / Financiamentos",
        financialType: "financial",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
      {
        code: "FDR.05",
        name: "Adiantamentos / Cauções",
        financialType: "transitory",
        affectsDre: false,
        affectsCashflow: true,
        affectsProfitability: false,
        requiresChannel: false,
        requiresAllocation: false,
      },
    ],
  },
];
